version: '3.8'

services:
  ecowitt_net:
    image: python:3.8-slim
    container_name: ecowitt_net_service
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && pytest"
    networks:
      - ecowitt_net_network
    ports:
      - "8000:8000"

volumes:
  ecowitt_net_volume:
    driver: local

networks:
  ecowitt_net_network:
    driver: bridge

configs: {}

secrets: {}
